### ISSUE TITLE
Endpoint in Azure functions

### ISSUE THREAD

**Issue by AstralisSomnium** [AstralisSomnium/Spread_Desktop#10]
Endpoint with following parameters:
+ Blockchain Adresse: From who the ADA was committed
+ ADA balance what was committed
+ Poolid
+ Email address which should be notified

Server-side listens on every entry:
+ If for one pool id the live stake plus SPRD ADA superiors the 1,5m ADA then all email address are notified to delegate now.

**Comment by aleincsharp** [comment]
The Endpoint will be implementet in Azure functions.

**Comment by AstralisSomnium** [comment]
@aleincsharp 
Another endpoint should also be available in order to read the total SPRD committed by people for one stake pool.
So a GET request with one argument of the stake pool id:
+ Return should be the total SPRD in ADA and if possible the number of delegators.

**Comment by AstralisSomnium** [comment]
Endpoints are implemented for DELETE and CREATE. SPRD client uses them with TEST codes.
After Beta phase we will exchange the codes with the production environment.
